server:
  port: 8080
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/sphere_auth"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-access-duration: 30 # in minute
  valid-refresh-duration: 10080 # in minute


app:
  account:
    admin:
      email: thuantn10
      password: abc123!@#
  token:
    max-refresh-token: 5


